version: 2
jobs:
  build:

    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install --global mocha
      - run: npm install --global tsc
      - run: npm install --global lerna
      - run: lerna bootstrap
      - run: lerna run compile