version: 2
jobs:
  build:

    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm install --global mocha
      - run: sudo npm install --global typescript
      - run: sudo npm install --global lerna@2.11.1
      - run: lerna bootstrap
      - run: lerna run compile
